[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_PRIVATE_TARGET = "server" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
