[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # jeśli chcesz pominąć middleware
    skipMiddleware = true

# definicja formularza Netlify
[[forms]]
  name = "contact"
  path = "app/api/contact/route.js"
