# netlify.toml

[build]
  command   = "npm run build"
  publish   = "out"

[build.environment]
  NODE_VERSION          = "20"
  NODE_ENV              = "production"
  NEXT_PUBLIC_BASE_URL  = "https://your-portfolio-site.netlify.app"

