[[build]]
  command = "npm run build"
  publish = "out"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://your-portfolio-site.netlify.app"

# Enable Netlify Forms for the contact form
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"