[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  NEXT_PUBLIC_BASE_URL = "https://your-portfolio-site.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
