[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  NEXT_PUBLIC_BASE_URL = "https://nyxtrael.com" # Zaktualizowana domena

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions"
  [plugins.inputs]
    forms = true