backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    files:
      - name: "illustrations"
        label: "Illustrations"
        file: "public/data/services.json"
        fields:
          - name: "illustrations"
            label: "Illustration Packages"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Artworks", name: "artworks", widget: "string" }
              - { label: "Features", name: "features", widget: "list", default: [] }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Button Text", name: "button", widget: "string" }
              - { label: "Recommended", name: "recommended", widget: "boolean", required: false }

      - name: "webDesign"
        label: "Web Design"
        file: "public/data/services.json"
        fields:
          - name: "webDesign"
            label: "Web Design Packages"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Features", name: "features", widget: "list", default: [] }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Button Text", name: "button", widget: "string" }
              - { label: "Recommended", name: "recommended", widget: "boolean", required: false }

      - name: "videoEditing"
        label: "Video Editing"
        file: "public/data/services.json"
        fields:
          - name: "videoEditing"
            label: "Video Editing Packages"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Features", name: "features", widget: "list", default: [] }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Button Text", name: "button", widget: "string" }
              - { label: "Recommended", name: "recommended", widget: "boolean", required: false }
