export const caseStudies = [
  {
    slug: "startup-landing",
    title: "BrightCRM – Landing Page for CRM Application",
    description: "A responsive landing page encouraging demo sign-ups.",
    thumbnail: "/images/startup-landing.jpg",
    path: "/case-studies/startup-landing",
    category: "SaaS",
    context: "Client project, SaaS startup – 2024",
    goal: "The client needed a fast, visually appealing CRM demo page to boost demo sign-ups and showcase core features.",
    role: "I handled the design, frontend development using Next.js, and implemented SEO strategies to improve visibility.",
    technologies: ["Next.js", "Tailwind CSS", "Netlify"],
    result: "Achieved a page load time of 1.4s and increased demo sign-ups by 22% within 2 weeks of launch.",
    isFeatured: true,
    challenges: "The main challenge was optimizing the page for speed while ensuring a visually rich experience with interactive elements.",
    solutions: "I used Next.js for static generation, optimized images with Next/Image, and implemented lazy-loading for non-critical assets.",
    screenshots: [
      { src: "/images/startup-landing-screenshot-1.jpg", alt: "BrightCRM landing page hero section" },
      { src: "/images/startup-landing-screenshot-2.jpg", alt: "BrightCRM demo sign-up form" },
    ],
    feedback: [
      { quote: "The landing page significantly boosted our sign-ups!", author: "Jane Doe, CEO at BrightCRM" },
    ],
    metrics: { signUpsIncrease: 22, pageLoadTime: "1.4s" },
  },
  {
    slug: "ecommerce-redesign",
    title: "ShopTrend – E-commerce Store Redesign",
    description: "Redesign of an e-commerce store with enhanced UX.",
    thumbnail: "/images/ecommerce-redesign.jpg",
    path: "/case-studies/ecommerce-redesign",
    category: "E-commerce",
    context: "Client project, E-commerce brand – 2023",
    goal: "The goal was to redesign an outdated e-commerce platform to improve user engagement and streamline the checkout process.",
    role: "I led the UI/UX design and frontend development using Next.js, focusing on usability and performance.",
    technologies: ["Next.js", "Tailwind CSS", "Netlify"],
    result: "Improved checkout conversion by 15% and delivered the project in just 3 weeks.",
    challenges: "The existing platform had a high bounce rate due to poor navigation and slow load times.",
    solutions: "I redesigned the navigation for better usability, optimized assets, and implemented a streamlined checkout flow with Next.js ISR.",
    screenshots: [
      { src: "/images/ecommerce-redesign-screenshot-1.jpg", alt: "ShopTrend homepage redesign" },
      { src: "/images/ecommerce-redesign-screenshot-2.jpg", alt: "ShopTrend checkout page" },
    ],
    feedback: [
      { quote: "The new design really improved our sales!", author: "Mark Smith, Founder at ShopTrend" },
    ],
    metrics: { conversionIncrease: 15, deliveryTime: "3 weeks" },
  },
  {
    slug: "saas-dashboard",
    title: "DataSync – SaaS Analytics Dashboard",
    description: "An intuitive analytics dashboard for a SaaS application.",
    thumbnail: "/images/saas-dashboard.jpg",
    path: "/case-studies/saas-dashboard",
    category: "SaaS",
    context: "Personal concept for portfolio – 2024",
    goal: "Create a modern SaaS dashboard UI to showcase my design and development skills in my portfolio.",
    role: "I designed the UI/UX and developed the frontend using Next.js, focusing on clean visuals and interactivity.",
    technologies: ["Next.js", "Tailwind CSS"],
    result: "Successfully showcased as a portfolio piece and received positive feedback from peers.",
    challenges: "Balancing aesthetics with functionality while ensuring the dashboard UI was intuitive for users.",
    solutions: "I used Tailwind CSS for rapid prototyping, implemented reusable components, and focused on a user-centric design approach.",
    screenshots: [
      { src: "/images/saas-dashboard-screenshot-1.jpg", alt: "DataSync dashboard overview" },
      { src: "/images/saas-dashboard-screenshot-2.jpg", alt: "DataSync analytics chart" },
    ],
    feedback: [
      { quote: "A great showcase of modern UI design!", author: "Alex Brown, Peer Developer" },
    ],
    metrics: { feedbackRating: "Positive" },
  },
  {
    slug: "photographer-portfolio",
    title: "PortraitPro – Photographer Portfolio Website",
    description: "A photo gallery with fast loading and fullscreen mode.",
    thumbnail: "/images/photographer-portfolio.jpg",
    path: "/case-studies/photographer-portfolio",
    category: "Portfolio",
    context: "Freelance for EU photographer – 2023",
    goal: "Develop a portfolio website for a professional photographer with a focus on fast loading and fullscreen photo viewing.",
    role: "I handled frontend development with Next.js and UI design, ensuring a seamless user experience.",
    technologies: ["Next.js", "Tailwind CSS", "Netlify"],
    result: "Increased client bookings by 30% and delivered the project in 4 weeks.",
    challenges: "Optimizing high-resolution images for fast loading without compromising quality.",
    solutions: "I used Next/Image for image optimization, implemented lazy-loading, and added a fullscreen mode with smooth transitions.",
    screenshots: [
      { src: "/images/photographer-portfolio-screenshot-1.jpg", alt: "PortraitPro gallery view" },
      { src: "/images/photographer-portfolio-screenshot-2.jpg", alt: "PortraitPro fullscreen mode" },
    ],
    feedback: [
      { quote: "My bookings went up significantly after launching this site!", author: "Sophie Müller, Photographer" },
    ],
    metrics: { bookingsIncrease: 30, deliveryTime: "4 weeks" },
  },
  {
    slug: "taskmaster-pwa",
    title: "TaskMaster – Task Management PWA",
    description: "A progressive web app for task management, working offline.",
    thumbnail: "/images/taskmaster-pwa.jpg",
    path: "/case-studies/taskmaster-pwa",
    category: "PWA",
    context: "Personal project – 2024",
    goal: "Build a progressive web app for task management that works offline and provides a native-like experience.",
    role: "I handled full-stack development with Next.js, focusing on UI/UX design and offline capabilities.",
    technologies: ["Next.js", "Tailwind CSS", "PWA APIs"],
    result: "Created a fully offline-capable app, successfully showcased in my portfolio.",
    challenges: "Ensuring reliable offline functionality and smooth performance on various devices.",
    solutions: "I implemented service workers with PWA APIs for offline support, used IndexedDB for data storage, and optimized for mobile performance.",
    screenshots: [
      { src: "/images/taskmaster-pwa-screenshot-1.jpg", alt: "TaskMaster task list view" },
      { src: "/images/taskmaster-pwa-screenshot-2.jpg", alt: "TaskMaster offline mode" },
    ],
    feedback: [
      { quote: "Really useful app for managing tasks offline!", author: "Chris Lee, Peer Developer" },
    ],
    metrics: { offlineCapability: "100%" },
  },
  {
    slug: "neon-ritual",
    title: "NeonRitual – AI Illustration Art Website",
    description: "An immersive website featuring animated AI illustrations.",
    thumbnail: "/images/neon-ritual.jpg",
    path: "/case-studies/neon-ritual",
    category: "Portfolio",
    context: "Personal project – 2024",
    goal: "Create an AI-generated art gallery with neon aesthetics and immersive animations to showcase creativity.",
    role: "I developed the frontend with Next.js and generated AI art using SDXL and ComfyUI.",
    technologies: ["Next.js", "SDXL", "ComfyUI"],
    result: "Highlighted my creativity and received positive community feedback.",
    challenges: "Integrating AI-generated art with smooth animations while maintaining performance.",
    solutions: "I used Next.js for static generation, optimized animations with CSS, and preloaded assets for a seamless experience.",
    screenshots: [
      { src: "/images/neon-ritual-screenshot-1.jpg", alt: "NeonRitual gallery view" },
      { src: "/images/neon-ritual-screenshot-2.jpg", alt: "NeonRitual animated illustration" },
    ],
    feedback: [
      { quote: "The neon aesthetic is stunning!", author: "Emma Davis, Art Enthusiast" },
    ],
    metrics: { communityFeedback: "Positive" },
  },
  {
    slug: "corporate-site",
    title: "CorpElevate – Corporate Website for Tech Firm",
    description: "A professional website for a tech firm to showcase services and attract clients.",
    thumbnail: "/images/corporate-site.jpg",
    path: "/case-studies/corporate-site",
    category: "Corporate",
    context: "Client project, Tech firm – 2024",
    goal: "Develop a professional corporate website to showcase the firm's services, team, and case studies, aiming to attract new clients.",
    role: "I handled UI/UX design, frontend development with Next.js, and ensured SEO optimization.",
    technologies: ["Next.js", "Tailwind CSS", "Vercel"],
    result: "Increased lead generation by 25% and delivered the project in 5 weeks.",
    challenges: "Creating a professional yet engaging design while ensuring fast load times for global users.",
    solutions: "I used Next.js SSG for fast load times, implemented a clean and modern design with Tailwind CSS, and optimized SEO with meta tags and structured data.",
    screenshots: [
      { src: "/images/corporate-site-screenshot-1.jpg", alt: "CorpElevate homepage" },
      { src: "/images/corporate-site-screenshot-2.jpg", alt: "CorpElevate services page" },
    ],
    feedback: [
      { quote: "The website has been a game-changer for our lead generation!", author: "John Carter, CEO at CorpElevate" },
    ],
    metrics: { leadIncrease: 25, deliveryTime: "5 weeks" },
  },
];